---
name: Lint, Build and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  init:
    name: Cancel Previous Runs on Branch
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs on Branch
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  prettier:
    name: "Test TS Prettier Format"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          dry: True
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          prettier_options: "--write **/*.ts"

  compile-test-cairo:
    name: Compile and Run Cairo Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starknet
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install NPM Dependencies
        run: npm install
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Cairo Format
        run: |
          find . -type f -name "*.cairo" -exec bash -c 'i="$1"; cairo-format $i | diff $i - >/dev/null 2>&1 && echo $i _PASSED_TEST_ || echo $i _FAILED_TEST_ | tee -a cairo-format-test.log' bash {} \;
          test -f cairo-format-test.log && echo Failed cairo-format test && exit 1
          echo "Passed Cairo Format test"
      - name: Run Cairo Compile
        run: npm run compile immutablex && npm run compile test/mocks
      - name: Start Devnet
        run: |
          docker pull shardlabs/starknet-devnet
          docker run -p 127.0.0.1:5000:5000 shardlabs/starknet-devnet --lite-mode &
          sleep 15s && echo "sleeping for 15s to let devnet start"
      - name: Run Cairo Tests
        run: npm run test

  compile-test-solidity:
    name: Compile and Run Solidity Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ethereum
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install NPM Dependencies
        run: npm install
      - name: Compile Solidity
        run: npx hardhat compile
      - name: Run Solidity Tests
        run: export REPORT_GAS=true; npx hardhat test
